# Generated by Django 5.2 on 2025-05-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_imgs/default_profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
