# Generated by Django 5.2 on 2025-04-29 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_user_is_active_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Metal', 'Metal'), ('eWaste', 'eWaste'), ('Organic', 'Organic')], max_length=100)),
                ('description', models.TextField()),
                ('waste_image', models.ImageField(blank=True, null=True, upload_to='waste_images/')),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Picked', 'Picked'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_waste_requests', to='api.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
