# Generated by Django 5.2 on 2025-05-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecomplaint',
            name='waste_type',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Metal', 'Metal'), ('eWaste', 'eWaste'), ('Organic', 'Organic'), ('Other', 'Other')], max_length=100),
        ),
    ]
