# Generated by Django 5.2 on 2025-05-06 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_is_active_alter_user_gender_and_more'),
        ('waste_management', '0002_alter_wastecomplaint_waste_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('Organic', 'Organic'), ('E-waste', 'E-waste'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('waste_image', models.ImageField(upload_to='complaints/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='api.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.DeleteModel(
            name='WasteComplaint',
        ),
    ]
