# Generated by Django 5.2 on 2025-05-12 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('api', '0006_user_is_active_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_assigned', models.BooleanField(default=False)),
                ('collectorassigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigne_collectors', to='api.user')),
                ('supervisorassigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigne_supervisors', to='api.user')),
            ],
        ),
    ]
