# Generated by Django 5.2 on 2025-05-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifycontact', '0003_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_mail', models.EmailField(max_length=254)),
                ('from_mail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
